### PR TITLE
Update youtube icon, fix 413

### LINKED ISSUE #413: Obsolete YouTube icon used in the site footer
YouTube dropped this style of social media icon used in the site footer years ago:

958a129a-0510-4440-ba6e-8d8cedbd5ab1

For the up to date icons see the [YouTube Brand Resources](https://www.youtube.com/yt/about/brand-resources/#logos-icons-colors) page.

### PR DESCRIPTION
**Pull request by meven**
After
screenshot_20181201_122204

Fix #413 

Reduces file size of youtube.svg from  3.13 KB  to 1.16 KB

### CODE REVIEW

**Comment by liigo** [comment]
Should not have a silid background color, according to other icons?

**Comment by meven** [comment]
It should indeed and it used to, I think the online svg optimizer I used to minimize the svg changed this.
I will fix it.

**Comment by meven** [comment]
Padding was incorrect, I updated the commit :
Current rendering is :
screenshot_20181201_173631

**Comment by chriskrycho** [comment]
Nice improvement! Thank you!

**Pull request merged**
